#!/usr/bin/env python

import sys
import rospy
from face_recognition_ros_wrapper.srv import *

def recognize_faces_client():
    rospy.wait_for_service('register_new_face')
    print("Found server service")
    try:
        register_new_face = rospy.ServiceProxy('register_new_face', RegisterNewFace)
        resp1 = register_new_face()
        return resp1.success_status
    except rospy.ServiceException as e:
        print("Service call failed: " + str(e))


if __name__ == "__main__":
    
    print("Response: " + str(recognize_faces_client()))
